version: '3.8'

services:
  nostr-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostr-app
    restart: unless-stopped
    volumes:
      # Optional: Custom nginx config if needed
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_web"
      - "traefik.http.routers.nostr-app.rule=Host(`nostr.edufeed.org`)"
      - "traefik.http.services.nostr-app.loadbalancer.server.port=8080"
      - "traefik.http.routers.nostr-app.entrypoints=websecure"
      - "traefik.http.routers.nostr-app.tls.certresolver=myresolver"
      # Optional: Add compression
    networks:
      - traefik_web
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  traefik_web:
    external: true
